name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - phase-3/Utpal-Raj-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

  
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh


      - name: Authenticate with Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

    
      - name: Deploy Frontend Service
        working-directory: frontend/my-app
        run: railway up --service frontend --docker
